# docker-compose.yaml
#api版本
version: "3"
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: registry.saas.hand-china.com/tools/mysql:5.6
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tk123456
    volumes:
    - ./mysql_data:/var/lib/mysql
    environment:
    - mysql_user=root
    - mysql_password=root
    - mysql_host=9.108.59.99:3306
    expose:
    - "3306"
    networks:
    - "c7nNetwork"
  helloworld:
    container_name: exam
    hostname: exam
    image: exam
    expose:
    - "8080"
    ports:
    - "8080:8080"
    networks:
    - "c7nNetwork"

networks:
  c7nNetwork:
    driver: bridge